spring:
  spring:
    jpa:
      properties:
        hibernate:
          event:
            merge:
              entity_copy_observer=allow:
  application:
    name: GestionaleAuto
  datasource:
    password: 'Stefanobru01.'
    driver-class-name: org.postgresql.Driver
    username: 'postgres'
    url: jdbc:postgresql://localhost:5432/gestionaleAuto
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: update
